# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e67701fa731ea71941fab402c7436d9d975ddb9db82d519ee654ffe761da9bac96a0227cd5b834212399e21730731ad59112bef821725f5c5b7ff4cd6e6aa3c

test:
  secret_key_base: 06d957e45cf46709f9cf22a0022f48766c99ee3c24b6d68372a63ddbe61005e6f24b763c42bf8c33a43d547899f936d83b75e39bdde2fdf8b13b77238d23d156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
